<?php
require '../vendor/autoload.php';
require_once '../vendor/swiftmailer/swiftmailer/lib/swift_required.php';
use Mailgun\Mailgun;

class Mailer{

    public function sendMessage($to,$subject,$corp){
        try{
            $from= array('ncornec@neuf.fr'=>'Gîtes St Jean de Monts');

            $transport = Swift_SmtpTransport::newInstance('smtp.sfr.fr', 25)
                ->setUsername('ncornec@neuf.fr')
                ->setPassword('h4qvz4j6')
            ;

            $mailer = Swift_Mailer::newInstance($transport);

            $message = Swift_Message::newInstance($subject)
                ->setFrom($from)
                ->setTo($to)
                ->setBody($corp, 'text/html')
            ;

            $mailer->send($message);
        }
        catch (\Exception $e){
            var_dump($e->getMessage());
        }
    }

    public function sendMessageMailgun($to,$subject,$corp)
    {
        try{
            // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
            $ch = curl_init();

            curl_setopt($ch, CURLOPT_URL, 'https://api.eu.mailgun.net/v3/mg.lecosyvendeen.fr/messages');
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($ch, CURLOPT_POSTFIELDS, [
                'from' => 'robin.cornec@laposte.net',
                'to' => $to,
                'subject' => $subject,
                'text' => $corp,
            ]);

            curl_setopt($ch, CURLOPT_USERPWD, 'api' . ':' . '7006f0ee0ef5bc5777a2f40d7a76440f-2d27312c-f4c29e7e');

            $result = curl_exec($ch);
            if (curl_errno($ch)) {
                echo 'Error:' . curl_error($ch);
            }
            curl_close ($ch);

        } catch (\Exception $exception) {
            var_dump($exception); die;
        }
    }

}
