version: "3"

volumes:
  mariadb-data:
    driver: local

services:
  nginx:
    image: nginx:latest
    volumes:
      - ../:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${APP_PORT}:80
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./php-fpm
    environment:
      WWWUSER: "${WWWUSER}"
    ports:
      - 9000:9000
    volumes:
      - ../:/var/www

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./mariadb/my.cnf:/etc/mysql/my.cnf
